### ISSUE TITLE
no dups here 

### ISSUE THREAD

**Issue by noornee** [cmd777/folder-dupe#1]
https://user-images.githubusercontent.com/71889751/222136192-25fb5f67-481a-41e7-8e8d-f78ce0e67ce7.mp4

**Comment by cmd777** [comment]
This bug won't work on mobile, as it requires the folder tree to be open (the screen has to be at least 768 pixels wide.)

But on a desktop, this still works. (as of 2023/3/1)
![stillworks](https://user-images.githubusercontent.com/83428931/222168242-afd68a57-33e5-45ff-be29-7510808c7fb0.png)

I'll update the README.

**Comment by noornee** [comment]
ohhh i see, alrightt 
I'll try it on my pc when i boot it up...

**Comment by noornee** [comment]
geez, i just realized that the reason it didnt show was cos i didnt have that feature enabled...my bad

**Comment by cmd777** [comment]
> geez, i just realized that the reason it didnt show was cos i didnt have that feature enabled...my bad
> 
> ![Screenshot_20230301-201625](https://user-images.githubusercontent.com/71889751/222242130-e4be0d12-ecfb-44d6-a8fd-be244d79a60b.png)

No worries.
